name: orchid
description: Silicon Valley (Season 4)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.9.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  barcode_scan:
    git:
      url: git://github.com/apptreesoftware/flutter_barcode_reader.git
      ref: 39ecc57bc0eef7b0465c891d900d2fb1f34a2390
  cupertino_icons: ^0.1.2
  dotted_border: ^1.0.4
  email_validator: ^1.0.3
  flare_flutter:
    git:
      url: git://github.com/2d-inc/Flare-Flutter.git
      ref: dev
      path: flare_flutter
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  flutter_html: ^0.11.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.18.0
  font_awesome_flutter: ^8.5.0
  http: ^0.12.0+3
  pointycastle: ^1.0.2
  provider: ^4.0.1
  qr_flutter: ^3.1.0
  rxdart: ^0.23.0
  shared_preferences: ^0.5.6
  sqflite: ^1.2.0
  url_launcher: ^5.4.1
  web3dart: ^1.2.1
  in_app_purchase:
    path: in_app_purchase
  dartjsengine: ^1.0.1
  # This doesn't support MacOS yet
  #flutter_secure_storage: ^3.3.3
  badges: ^1.1.1
  uuid: 2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/docs/help/
    - assets/flare/
    - assets/images/
    - assets/svg/

flutter_intl:
  enabled: true
