name: orchid
description: Silicon Valley (Season 4)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.9.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  badges: 1.2.0
  # XXX: use https://pub.dev/packages/firebase_ml_vision
  # that said, this library has been *discontinued*
  # this library can be upgraded to at least 3.0.1
  barcode_scan: 2.0.2
  cupertino_icons: 1.0.2
  dartjsengine: 1.0.1
  dotted_border: 2.0.0+2
  email_validator: 2.0.1
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  flutter_html: ^3.0.0-alpha.2
  flutter_localizations:
    sdk: flutter
  #flutter_secure_storage: 3.3.5 # XXX: macOS
  flutter_svg: 1.0.3
  font_awesome_flutter: 9.0.0
  http: 0.13.4
  in_app_purchase:
    path: in_app_purchase
  intl: 0.17.0
  jdenticon_dart: 2.0.0
  percent_indicator: 3.0.1
  pointycastle: 3.5.0
  provider: 5.0.0
  qr_flutter: 4.0.0
  rxdart: 0.25.0
  shared_preferences: 2.0.12
  styled_text: 3.0.4
  sqflite: 2.0.0+3
  url_launcher: 6.0.3
  uuid: 3.0.5
  web3dart: 2.3.3
  window_size:
    path: flutter-desktop-embedding/plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.11.0
  #build_runner:
  #flutter_gen_runner: 4.1.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/docs/help/
    - assets/images/
    - assets/svg/
    - assets/svg/chains/
    - assets/svg/tokens/

  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
          weight: 400
        - asset: assets/fonts/Baloo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Baloo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Baloo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
          weight: 800

# This is for the localizely intellij plugin
flutter_intl:
  enabled: false
