name: orchid
description: Silicon Valley (Season 4)
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.9.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  badges: 1.2.0
  browser_detector: 2.0.0
  cupertino_icons: 1.0.2
  dartjsengine: 1.0.1
  dotted_border: 2.0.0+2
  email_validator: 2.0.1
  flutter:
    sdk: flutter
  flutter_cupertino_localizations: 1.0.1
  flutter_html: 3.0.0-alpha.6
  flutter_localizations:
    sdk: flutter
  #flutter_secure_storage: 3.3.5 # XXX: macOS
  flutter_svg: 1.0.3
  font_awesome_flutter: 9.0.0
  http: 0.13.4
  in_app_purchase_storekit: 0.3.4
  in_app_purchase_android: 0.2.3+7
  intl: 0.17.0
  jdenticon_dart: 2.0.0

  # Tracking this issue which has been merged but is not yet in a tagged release.
  # https://github.com/juliansteenbakker/mobile_scanner/issues/241
  mobile_scanner:
    git:
      url: https://github.com/juliansteenbakker/mobile_scanner.git
      ref: 9e4e9a167980f8413c1d8860873e582d0747edd9

  percent_indicator: 3.0.1
  pointycastle: 3.5.0
  provider: 5.0.0
  qr_flutter: 4.0.0
  rxdart: 0.25.0
  shared_preferences: 2.0.12
  styled_text: 6.0.0
  sqflite: 2.0.0+3
  url_launcher: 6.0.3
  uuid: 3.0.5
  web3dart: 2.3.3
  window_size:
    path: flutter-desktop-embedding/plugins/window_size

dev_dependencies:
  dart_code_metrics: 4.21.3
  flutter_test:
    sdk: flutter
  pedantic: 1.11.0
  #build_runner:
  #flutter_gen_runner: 4.1.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/docs/help/
    - assets/images/
    - assets/svg/
    - assets/svg/chains/
    - assets/svg/tokens/

  fonts:
    - family: Baloo2
      fonts:
        - asset: assets/fonts/Baloo2-Regular.ttf
          weight: 400
        - asset: assets/fonts/Baloo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Baloo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Baloo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo2-ExtraBold.ttf
          weight: 800

# This is for the localizely intellij plugin
flutter_intl:
  enabled: false
